<?php

namespace Services;

require_once __DIR__."/../../../repository/AuthRepo/AuthRepo.php";

class Authentication
{
    private $rotateStatus = true;

    /**
     * Issuing refresh tokens generated by a secure way
     * 
     * @return string Generated refresh token
     */
    public function issueRefreshToken()
    {
        return base64_encode(bin2hex(openssl_random_pseudo_bytes(32).time()));
    }

    /**
     * check whether the refresh token exists or if its exists check for
     *                  expiration time
     * 
     * @return boolean validation status
     */
    public static function isRefreshTokenValid($session)
    {
        if($session === null || $session->isExpired())
            return false;
        return true;
    }

    /**
     * Enabling the rotate mechanism for refresh tokens
     * 
     * @return void
     */
    public function enableRotate()
    {
        $this->rotateStatus = true;
    }

    /**
     * Disabling the rotate mechanism for refresh tokens
     * 
     * @return void
     */
    public function disableRotate()
    {
        $this->rotateStatus = false;
    }

    /**
     * Check the rotation status
     * 
     * @return boolean Rotation status
     */
    public function isRotateEnable()
    {
        return $this->rotateStatus;
    } 

}